service: nacarat

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline

custom:
  serverless-offline:
    #port: 4001

provider:
  name: aws
  runtime: nodejs6.10

functions:
  query:
    handler: handler.queryProducts
    events:
      - http:
          path: /products
          method: GET
          cors: true
  get:
    handler: handler.getProduct
    events:
      - http:
          path: /products/{id}
          method: GET
          cors: true
  create:
    handler: handler.createProduct
    events:
      - http:
          path: /products
          method: POST
          cors: true
